WebScrappingD/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("scrapper.urls"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

scrapper/urls.py
from django.urls import path

from scrapper import views

app_name = "scrapper"

urlpatterns = [
    path('scrapper', views.scrapper, name="scrapper"),
    path('top', views.top_movies, name="top"),
    path('latest', views.latest_movies, name="latest"),
    path('single', views.single, name="single"),
    path('', views.home, name="home"),
]

scrapper/models.py
from django.db import models

# Create your models here.

scrapper/views.py
from collections import Counter
import json
import re

import requests
from bs4 import BeautifulSoup
from django.http import HttpResponse
from django.shortcuts import render
import pandas as pd


# Create your views here.
def scrapper(request):
    searched = request.GET.get("s", "")
    movies = []
    movies = mobo(movies, searched)
    movies = digi(movies, searched)
    movies = set_order(movies, searched)
    jsonify = json.dumps(
        {"result": movies},
        ensure_ascii=False,
    )
    return HttpResponse(jsonify, content_type="application/json")


def latest_movies(request):
    searched = ""
    movies = []
    movies = mobo(movies, searched)
    movies = digi(movies, searched)
    movies = set_order(movies, searched)
    jsonify = json.dumps(
        {"result": movies[:10]},
        ensure_ascii=False,
    )
    return HttpResponse(jsonify, content_type="application/json")


def top_movies(request):
    movies = []
    movies = get_top_movies()
    data = {}
    data["result"] = movies[:7]
    jsonify = json.dumps(
        data,
        ensure_ascii=False,
    )
    return HttpResponse(jsonify, content_type="application/json")


def get_top_movies():
    url = f"https://digimovie.city/"
    movies = []
    try:
        page = requests.get(url)
        content = page.content
        soup = BeautifulSoup(content, "html.parser")
        movies_list = (
            soup.find(class_="index_slider")
                .find(class_="container")
                .find(class_="inner_index_slider")
        )
        if movies_list:
            for item in movies_list.find_all(class_="item_slider_index"):
                movie = {}
                title = item.find(class_="poster").find("a")["title"]
                movie["title"] = string_prettier(title)
                movie["default_img"] = "https://mobomovie1.xyz/img/default.png"
                movie["site"] = "https://digimovie.city"
                movie["rating"] = float(
                    string_prettier(
                        item.find(class_="poster_active")
                            .find(class_="left_side")
                            .find("strong")
                            .text
                    )
                )
                movie["image"] = item.find(class_="poster").find("a").find("img")["src"]
                movie["link"] = item.find(class_="poster").find("a")["href"]
                movie["extra_info"] = ""
                movies.append(movie)
    except Exception as e:
        raise e
    return movies


def string_prettier(string):
    string = string.strip()
    escapes = "".join([chr(char) for char in range(1, 32)])
    translator = str.maketrans("", "", escapes)
    string = string.translate(translator)
    without_space = re.sub(" +", " ", string)
    return without_space


def set_order(old_list, searched):
    def check_exist(arr1, arr2):
        result = False
        for item in arr1:
            if item in arr2:
                result = True
        return result

    def get_array(string):
        splitter = string.lower().split(" ")
        final = []
        for word in splitter:
            w_index = splitter.index(word)
            j = w_index + 1
            while j != len(splitter):
                final.append(" ".join(splitter[w_index: j + 1]))
                j += 1
        return final + splitter

    def start(searched_str):
        searched_str = searched_str.lower()
        result = []
        result_per = []
        for movie in old_list:
            title = " ".join(get_en_words(movie["title"])).lower()
            coms = get_array(title)
            if check_exist(searched_str.split(" "), coms):
                calculate(coms, movie, result, result_per, searched_str, title)
            else:
                result.append(movie)
                result_per.append(0)
        df = pd.DataFrame({"Movie": result, "Per": result_per})
        df = df.sort_values(by="Per", ascending=False)
        arr = df[["Movie"]].to_numpy()
        arr2 = [movie[0] for movie in arr]
        return arr2

    def calculate(coms, movie, result, result_per, searched_str, title):
        for com in coms:
            if com == searched_str:
                chopped = split_str(title, searched_str)
                n_chars = len(chopped)
                counter = Counter(chopped)
                occ_pct = {}
                for char, occ in counter.most_common():
                    occ_pct[char] = (occ / n_chars) * 100
                if searched_str in occ_pct:
                    result.append(movie)
                    searched_index = chopped.index(searched_str)
                    priority = occ_pct[searched_str] * (
                            (len(chopped) - searched_index) / len(chopped)
                    )
                    result_per.append(priority)

    def split_str(string, split_by):
        string = string.strip()
        string = string.split(" ")
        split_by_arr = split_by.split(" ")
        ded = []
        for item in string:
            if item not in split_by_arr:
                ded.append(item)
        ded.insert(string.index(split_by_arr[0]), split_by)
        return ded

    return start(searched)


def single(request):
    link = request.GET.get("link", "")
    if link.split("/")[2].strip() == "digimovie.city":
        return get_digi_single(link)
    elif link.split("/")[2].strip() == "mobomovie1.xyz":
        return get_mobo_single(link)


def get_digi_single(link):
    movie = {}
    try:
        page = requests.get(link)
        content = page.content
        soup = BeautifulSoup(content.decode('utf-8', 'ignore'), "html.parser")
        details = {}
        movie["actors"] = []
        movie["related"] = []
        for detail in soup.find(class_="single_meta_data").find("ul").find_all("li"):
            label = detail.find(class_="lab_item")
            value = detail.find(class_="res_item")
            details[string_prettier(label.text)] = string_prettier(value.text)
        movie['details'] = "__".join([f"{details[key]}_{key}" for key in details])
        story_tag = soup.find(class_="single_meta_data").find(class_="plot_text")
        movie["story"] = string_prettier(story_tag.text)
        for actor in soup.find(class_="cast_body").find_all(class_="item_cast"):
            name = actor.find(class_="actor_meta").find("h3")
            image = actor.find(class_="actor_image").find("img")["src"]
            together = {"name": string_prettier(name.text), "image": image}
            movie["actors"].append(together)
        for realated in soup.find(class_="related_posts").find_all(
                class_="item_small_loop"
        ):
            title = realated.find("a").find("h3")
            image = realated.find(class_="cover").find("img")
            link = realated.find("a")["href"]
            together = {
                "title": string_prettier(title.text),
                "image": image["src"],
                "link": link,
            }
            movie["related"].append(together)
            extra_info = []
        if soup.find(class_="subtitles_item"):
            extra_info.append("زیرنویس چسبیده")
        movie['extra_info'] = "__".join(extra_info)
        rating = soup.find(class_="imdb_holder_single").find("strong").text
        movie["rating"] = float(string_prettier(rating))
        return HttpResponse(json.dumps({"result": [movie]}, ensure_ascii=False), content_type="application/json")
    except Exception as e:
        jsonify = json.dumps({"error": "Something went wrong!"})
        #         raise(e)
        return HttpResponse(jsonify, content_type="application/json")


def get_mobo_single(link):
    movie = {}
    try:
        page = requests.get(link)
        content = page.content
        soup = BeautifulSoup(content.decode('utf-8', 'ignore'), "html.parser")
        details = {}
        movie["actors"] = []
        movie["related"] = []
        for detail in soup.find(class_="details").find("ul").find_all("li"):
            label = detail.find("h4")
            if label:
                value = detail.find("a")
                details[string_prettier(label.text)] = string_prettier(
                    value.text
                )
        movie['details'] = "__".join([f"{details[key]}_{key}" for key in details])
        story_tag = soup.find(class_="summary")
        story_tag.b.decompose()
        movie["story"] = string_prettier(story_tag.text)
        #         movie["story"] = story_tag.text
        for actor in soup.find(class_="cast").find_all(class_="cast-item"):
            name = actor.find("strong")
            image = actor.find("img")["data-src"]
            together = {"name": string_prettier(name.text), "image": image}
            movie["actors"].append(together)
        for realated in soup.find(id="movie-scroll").find_all(class_="scroll-item"):
            title = realated.find(class_="scroll-title")
            image = realated.find("img")
            link = realated.find("a")["href"]
            together = {
                "title": string_prettier(title.text),
                "image": image["src"],
                "link": link,
            }
            movie["related"].append(together)
            extra_info = []
        for extra in soup.find(class_="extra-info").find_all("p"):
            if extra.find(class_="check"):
                extra_info.append(string_prettier(extra.text))
        movie['extra_info'] = "__".join(extra_info)
        movie["rating"] = float(
            string_prettier(soup.find(class_="imdb-post").find_all("b")[0].text)
        )
        return HttpResponse(json.dumps({"result": [movie]}, ensure_ascii=False), content_type="application/json")
    except Exception as e:
        jsonify = json.dumps({"error": "Something went wrong!"})
        # raise (e)
        return HttpResponse(jsonify, content_type="application/json")


def get_en_words(string):
    list_words = []
    for word in string.strip().split(" "):

scrapper/templates/scrapper/index.html
{% load static %}
<html>

<head>
          <meta charset="UTF-8" dir="rtl">
          <meta name="viewport"
                    content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
          <meta http-equiv="X-UA-Compatible" content="ie=edge">
          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
                    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
                    crossorigin="anonymous">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
                    integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
                    crossorigin="anonymous" referrerpolicy="no-referrer" />
          <link rel="stylesheet" href="{% static 'iransanse/fontiran.css' %}">
          <link rel="stylesheet" href="{% static 'css/index.css' %}">
          <link rel="stylesheet" href="{% static 'css/utilities.css' %}">
          <title>Home</title>
</head>

<body>
          <div class="header-search">
                    <form class='form' id="form">
                              <div class="form-group">
                                        <input type="text" name="name" placeholder="Search..." class="en"
                                                  autoComplete="off" id="search" />
                                        <button type='submit'><i class="fa fa-search"></i></button>
                              </div>
                    </form>
          </div>
          <div class='content'>
                    <ul>
                    </ul>
          </div>
          <div class="please-wait close">
                    <div class="spinner-border text-light" role="status">
                              <span class="visually-hidden">Loading...</span>
                    </div>
          </div>
          <div class="not-found">
                    <p class="en">Not found!</p>
          </div>
          <div class="error show">
                    <p class="en"></p>
          </div>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
                    integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
                    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
                    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
                    crossorigin="anonymous">
                    </script>
          <script>
                    const form = document.getElementById('form');
                    const content = document.querySelector('.content ul');
                    let searched = $('#search').val();

                    $('#search').keyup(function (e) {
                              searched = $('#search').val();
                    });

                    form.onsubmit = (e) => {
                              e.preventDefault();
                              sendReq();
                    }

                    function sendReq() {
                              clearError();
                              clearNotFound();
                              setLoading();
                              var xhr = new XMLHttpRequest();
                              var formData = new FormData();
                              formData.append('name', searched);
                              xhr.open("POST", "{% url 'scrapper:scrapper' %}");
                              xhr.onload = () => {
                                        clearLoading();
                                        let res = JSON.parse(xhr.responseText);
                                        if (res.length !== 0) {
                                                  setContent(res);
                                        } else {
                                                  setContent([]);
                                                  setNotFound();
                                        }
                              }
                              xhr.onerror = (err) => {
                                        setContent([]);
                                        setError('Something went wrong!');
                              }
                              xhr.send(formData);
                    }

                    function setContent(items) {
                              let new_list = renderListing(items);
                              content.innerHTML = new_list;
                    }

                    function renderDetails(details) {
                              let detailsList = '';
                              for (const key in details) {
                                        if (Object.hasOwnProperty.call(details, key)) {
                                                  const element = details[key];
                                                  detailsList +=
                                                            ` <p><span class="label">${key}</span> <span>${element}</span></p>`
                                                            ;
                                        }
                              }
                              return detailsList;
                    }
                    function renderExtra(extra) {
                              let extraList = '';
                              for (let i = 0; i < extra.length; i++) {
                                        const element = extra[i];
                                        extraList +=
                                                  `<span class="extra_item"><span>${element}</span></span>`
                                                  ;
                              }
                              console.log(extraList);
                              return extraList;

                    }
                    function renderListing(items) {
                              let itemList = '';
                              items.map(item => {
                                        return itemList +=
                                                  `<li>
                                                            <div class="img">
                                                                      <img src=${item.img} alt="" />
                                                            </div>
                                                            <div class="id">${document.querySelectorAll('.content li').length}</div>
                                                            <div class="info">
                                                                      <div class="header">
                                                                                <h2 class="name" >${item.title}</h2>
                                                                      </div>
                                                                      <p class="site">سایت: <a class="en" target="_blank" href="${item.site}">${item.site}</a></p>
                                                                      ${renderDetails(item.details)}
                                                                      <p>${item.story}</p>
                                                                      <p class='extra'><span class="label">نوع فیلم:  </span>${renderExtra(item.extra_info)}</p>
                                                                      <div class="more">
                                                                                <a target="_blank" href=${item.link} class="btn btn-blue">بیشتر</a>
                                                                      </div>
                                                            </div>
                                                  </li>`;
                              });
                              return itemList;
                    }

                    const errorEl = document.querySelector('.error');

                    function setError(error) {
                              errorEl.querySelector('p').innerText = error;
                              errorEl.classList.add('show');
                    }

                    function clearError() {
                              errorEl.querySelector('p').innerText = '';
                              errorEl.classList.remove('show');
                    }
                    const notFoundEl = document.querySelector('.not-found');

                    function setNotFound(error) {
                              notFoundEl.classList.add('show');
                    }

                    function clearNotFound() {
                              notFoundEl.classList.remove('show');
                    }
                    const loadingEl = document.querySelector('.please-wait');

                    function setLoading() {
                              loadingEl.classList.remove('close');
                    }

                    function clearLoading() {
                              loadingEl.classList.add('close');
                    }

          </script>
</body>

</html>